/**
 * Centralized strings for UI and notifications.
 */

export const STRINGS = {
  APP: {
    NAME: 'SYNTHIA',
    WORDMARK: 'SYNTHIA',
    VERSION: 'v0.1.0-alpha',
  },
  STATUS: {
    CONNECTED: 'CONNECTED',
    DISCONNECTED: 'DISCONNECTED',
    CONNECTING: 'CONNECTING',
    ERROR: 'ERROR',
    RTT: 'RTT',
    INFERENCE: 'Inference',
    FRAME: 'Frame',
    CYCLE: 'Cycle',
    FPS: 'FPS',
    HEARTBEAT: 'Heartbeat',
    LIGHT: 'Light',
    DAY: 'DAY',
    NIGHT: 'NIGHT',
    FALLING: 'FALLING',
    GROUNDED: 'GROUNDED',
  },
  GOD_MODE: {
    TITLE: 'GOD MODE',
    PHYSICS: 'Physics',
    BODY: 'Body',
    DIRECTIVE: 'Directive',
    SPAWNER: 'Spawner',
    CONNECTION: 'Connection',
    FREE_WILL: 'FREE WILL MODE',
    TRAINING: 'TRAINING',
    SET_GOAL: 'Set Goal',
    CLEAR_GOAL: 'Clear Goal',
    ENDPOINT_URL: 'Endpoint URL',
    CONNECT: 'Connect',
    DATABASE: 'Database',
    GRAVITY: 'GRAVITY',
    FRICTION: 'FRICTION',
    MOVEMENT_SMOOTHING: 'Movement Smoothing',
    TRAINING_MODE_LABEL: 'TRAINING MODE',
    OBJECT_SPAWNER_TITLE: 'Object Spawner',
    SPAWN_BUTTON: 'Spawn',
    EXPORT_BUTTON: 'Export',
    RESET_POSE: 'Reset Pose',
    FULL_RESET: 'Full Reset',
    SET_SPAWN: 'Set Spawn Here',
    SAVE_WORLD: 'Save World',
    LOAD_WORLD: 'Load World',
    BODY_MODE_RIGID: 'Rigid',
    BODY_MODE_RAGDOLL: 'Ragdoll',
    BODY_TYPE: 'Body Type',
    OBJECT_SPAWNED_ORIGIN: (name: string) => `${name} spawned at origin`,
  },
  AGENT: {
    NAME_LABEL: 'SYNTHIA-01',
    THOUGHT_BANK: 'Thought Bank',
    INJECTION_PLACEHOLDER: 'Inject a thought...',
    MEMORY_VIEWER: 'Memory Viewer',
    SENDING_TO_AI: 'SENDING TO AI',
    RUNG_LABEL: 'Rung',
    MEMORIES_LABEL: 'Memories',
    NO_MEMORIES: 'No memories archived',
    VOID_SILENT: 'The void is silent...',
    SKILLS_LOWER: (count: number) => `${count} skills`,
  },
  EXPORT: {
    TITLE: 'Export Data',
    PREVIEW_ROWS: '~2,847 rows',
    PREVIEW_SIZE: '~340MB',
    START_EXPORT: 'Start Export',
    EXPORTING: (progress: number) => `Exporting ${progress}%`,
    SELECT_FORMAT: 'Select Format',
    OPTIONS: 'Options',
    ESTIMATED_SIZE: 'Estimated Size',
    INCLUDE_VISUALS: 'Include visual frames',
    INCLUDE_THOUGHTS: 'Include thought stream',
    INCLUDE_JOINTS: 'Include joint states',
    // Export types
    EXPORT_TYPE: 'Export Type',
    EXPORT_TYPE_DATASET: 'Dataset',
    EXPORT_TYPE_DATASET_DESC: 'Training data (LeRobot, JSONL, CSV)',
    EXPORT_TYPE_FRAMES: 'Frames ZIP',
    EXPORT_TYPE_FRAMES_DESC: 'Download raw frame images',
    EXPORT_TYPE_THOUGHTS: 'Thoughts Report',
    EXPORT_TYPE_THOUGHTS_DESC: 'Human-readable AI thoughts',
    EXPORT_TYPE_SESSION_FULL: 'Session Full',
    EXPORT_TYPE_SESSION_FULL_DESC: 'Complete session archive',
    // Side panel
    PREVIEW_PANEL: 'Export Preview',
    NO_SELECTION: 'Select export options to preview',
    SCOPE_LABEL: 'Data Scope',
    TIER_LABEL: 'Memory Tiers',
    FILTERS: 'Filters',
    // Tier descriptions
    TIER_INFO: 'Memory Tier Info',
    TIER_1_NAME: 'Working Memory',
    TIER_1_DESC: 'Short-term, most recent memories. Highest priority for AI recall via vector search. Pruned after 2 most recent sessions.',
    TIER_2_NAME: 'Episodic Memory',
    TIER_2_DESC: 'Medium-term memories. Included in vector search. Pruned after 20 most recent sessions.',
    TIER_3_NAME: 'Long-term / Archival',
    TIER_3_DESC: 'Lowest priority. Not included in vector search. Pruned first (after 2 sessions). Default tier for most memories.',
    // Session full sub-options
    INCLUDE_SKILLS: 'Include skills',
    INCLUDE_MOTOR_PROGRAMS: 'Include motor programs',
    // Session picker
    SESSION_PICKER_TITLE: 'Select Sessions',
    SESSION_MEMORY_COUNT: (count: number) => `${count} memories`,
    NO_SESSIONS: 'No sessions found',
    SESSIONS_LOADING: 'Loading sessions...',
  },
  TOASTS: {
    CONNECT_SUCCESS: 'Successfully connected to endpoint',
    CONNECT_ERROR: 'Failed to connect to endpoint',
    EXPORT_STARTED: 'Data export initialized',
    EXPORT_SUCCESS: 'Export complete',
    GOAL_SET: 'New directive established',
    OBJECT_SPAWNED: 'Object added to scene',
    THOUGHT_INJECTED: 'Thought successfully injected into neural stream',
    RAPIER_LOAD_FAIL: 'Failed to initialize physics engine',
    RAPIER_RETRY: 'Retry Physics Init',
    WEBGL_NOT_SUPPORTED: 'WebGL is not supported on this browser',
    MOTOR_PROGRAM_INVALID: 'Invalid motor program JSON detected',
    NAN_VELOCITY_DETECTED: 'Physics instability detected. Auto-resetting...',
    COLLIDER_CREATION_FAIL: 'Failed to create object collider',
    WORLD_SAVED: 'World state saved to local storage',
    WORLD_LOADED: 'World state restored from session',
  },
  WORLD: {
    LOADING: 'INITIALIZING SIMULATION...',
  }
};
